### ISSUE TITLE
backend(unique) service장애시 처리

### ISSUE THREAD

**Issue by alkee-allm** [alkee-allm/k2proto#38]
backend(서버들의 서버) server 가  장애가 발생한 경우, 그리고 다시 재 연결이 된 경우에 알맞은 동작(서비스 계속 진행)을 수행해야한다.

#37 작업진행이 선행 되어야 할 것.

**Comment by alkee-allm** [comment]
테스트를 위해서는 별도의 instance 로 실행 가능해야한다. 이를 위한 환경 구성은, 기존과 같이 client - server(ServerManager) 를 visual studio(debugger)로 실행하고, 다른 서버를 빌드경로(`bin/Debug/netcoreapp3.1`)에서 복사해 새로운 instance 설정으로 실행하면 될 듯. 따라서 visual studio 에서의 설정(`appsettings.development.json`)은

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Grpc": "Information",
      "Microsoft": "Information"
    }
  },
  "K2": {
    "ServerId": "ServerManager",
    "ListeningPort": 4684,
    "EnableUserSessionBackend": false,
    "EnablePushService": false,
    "EnableInitService": false,
    "EnablePushSampleService": false,
    "EnableSimpleSampleService": false
  }
}
```

와 같고 복사되어 실행될 서버는 `K2svc.exe http://localhost:4684` 와 같이 실행.

하지만, 
https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Program.cs#L41-L49

와 같이 custom 하게 configuration 을 읽고 있기 때문에 `appsettings.development.json` 설정을 override 하지 않는 현상이 나타남. 따라서

`.AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json"` 추가.

별도의 instance 에서 실행하기 위한 환경(batch files) : [instanceConfig.zip](https://github.com/alkee-allm/k2proto/files/5191999/instanceConfig.zip)

**Comment by alkee-allm** [comment]
https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Background/ServerManagementBackground.cs#L84-L86

Backend ServerManager server 만 실행하는 경우 config 의 backend-address 와 `DefaultValues.SERVER_MANAGEMENT_BACKEND_ADDRESS` 가 달라 Register 가 계속 실패. 그렇다고 Register 를 하지 않게되면, backend server 들을 묶어 띄우는 경우에 ServerManager 이외의 다른 service 상태를 알 수 없게된다.

```csharp
#region helper
internal bool IsThisServerManager => string.IsNullOrEmpty(UserSessionBackendAddress);
internal string LocalServerManagerAddress => $"{ServiceScheme}://localhost:{ListeningPort}";
internal string ServerManagerAddress => IsThisServerManager ? LocalServerManagerAddress : RemoteServerManagerAddress;
#endregion
```

와 같은 helper 를 이용해 `ServerManagerAddress` 설정

**Comment by alkee-allm** [comment]
`SessionManager` 를 분리해 실행(parameter 에 ServerManagerAddress 사용)했으나, `Register` 가 도착하지 않는다.

https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Program.cs#L54
와 같이 configuration 을 업데이트 한 후

https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Program.cs#L60-L67
HostBuilder 에 추가를 했지만,

https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Startup.cs#L22-L26
Startup 에 injection 되지 않아, [`GetSection`](https://docs.microsoft.com/ko-kr/dotnet/api/system.configuration.configuration.getsection?view=dotnet-plat-ext-3.1)을 이용하는데, 이 전에 변경된 내용이 반영되지 않아 생기는 문제.
(#3, #36 에 걸친 configuration 수정 참고)

즉, Program.cs 에서 [GetSection 을 이용해 configuration 을 얻고 이를 수정](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Program.cs#L51-L54)한 후 StartUp 에서 [GetSection 을 통해 다시 configuration 을 얻어](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Startup.cs#L25)오면서 이전에 수정된 내용이 반영되지 않는 문제.

**Comment by alkee-allm** [comment]
StartUp 에서 직접 `ServiceConfiguration`을 얻어 사용할 수 있으면 좋은데, `System.InvalidOperationException: 'The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection.'` 발생.

[`CreateHostBuilder`](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Program.cs#L60) 내에서 직접 ServiceConfiguration singleton 을 등록하는 방식으로 수정. 여기저기에서 service 를 추가하는것이 맘에 들지는 않지만...

**Comment by alkee-allm** [comment]
instance 분리된 ServerManager 기능을 테스트해보려 [push sample service](https://github.com/alkee-allm/k2proto#pushsampleservice)의 [`Broadcast`](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/proto/sample.proto#L20) 테스트.

기능 동작은 하지만 ServerManager 쪽에
```
info: K2svc.Backend.ServerHostBackend[0]
      0 broadcasted message :
```
와 같이 0 count 메시지가 보인다. broadcast 할 때, frontend service(push service) 뿐 아니라 backend(자기자신)에게도 모든 연결된 서버들에 대해 broadcast 요청을 하기 때문인 듯.

**Comment by alkee-allm** [comment]
현재 ServerManager 장애시 재연결되는 서버에 지속적으로 ping 만 보내게 되고, 이때문에 

```
warn: K2svc.Background.ServerManagementBackground[0]
      ServerManagement timer is busy(1)
warn: K2svc.Background.ServerManagementBackground[0]
      ServerManagement timer is busy(2)
warn: K2svc.Background.ServerManagementBackground[0]
      ERROR on ping : Error starting gRPC call. HttpRequestException: 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했 습니다. SocketException: 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다.
info: K2svc.Background.ServerManagementBackground[0]
      Server Management backend not OK ping back.
```

와 같은 [ping response](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/proto/backend.proto#L117-L119)를 받는데, [이는 ServerManager쪽에서 이미 데이터를 들고있지 않은 상황](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Backend/ServerManagerBackend.cs#L129-L139)이므로, 때 다시 register 를 해야할 것.

**Comment by alkee-allm** [comment]
SessionManager 의 경우, [push sample service](https://github.com/alkee-allm/k2proto#pushsampleservice)의 [`Message` method](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/proto/sample.proto#L21) 이용해 테스트.

```
예외 발생: 'System.UriFormatException'(System.Private.Uri.dll)
'K2svc.exe'(CoreCLR: clrhost): 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Diagnostics.StackTrace.dll'을(를) 로드했습니다. 기호를 로드하지 않고 건너뛰었습니다. 모듈이 최적화되어 있고 '내 코드만' 디버거 옵션을 사용하도록 설정되어 있습니다.
'K2svc.exe'(CoreCLR: clrhost): 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Reflection.Metadata.dll'을(를) 로드했습니다. 기호를 로드하지 않고 건너뛰었습니다. 모듈이 최적화되어 있고 '내 코드만' 디버거 옵션을 사용하도록 설정되어 있습니다.
'K2svc.exe'(CoreCLR: clrhost): 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.IO.MemoryMappedFiles.dll'을(를) 로드했습니다. 기호를 로드하지 않고 건너뛰었습니다. 모듈이 최적화되어 있고 '내 코드만' 디버거 옵션을 사용하도록 설정되어 있습니다.
Grpc.AspNetCore.Server.ServerCallHandler: Error: Error when executing service method 'PushBegin'.

System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(String address)
   at K2svc.Net.GrpcClients.GetChannel(String backendAddress) in C:\work\local\K2\K2svc\Net\Grpc.cs:line 31
   at K2svc.Net.GrpcClients.GetClient[T](String backendAddress) in C:\work\local\K2\K2svc\Net\Grpc.cs:line 15
   at K2svc.Frontend.PushService.PushBegin(Null request, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\work\local\K2\K2svc\Frontend\PushService.cs:line 41
   at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest request, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest request, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass4_0.<<ServerStreamingPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass4_0.<<ServerStreamingPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

exception 발생. 확인해보니 [`config.UserSessionBackendAddress`](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/Frontend/PushService.cs#L41) 가 비어있다.

현재, Server 가 register 되면 ServerManager 만 update 되고, backend server 가 추가로 register 되었을 때, 이를 모든 server 에 전파하는 protocol 이 없다. 이를 추가해야할 것.

**Comment by alkee-allm** [comment]
SessionManager 가 없는 상황에서 client 를 연결시키면 SessionManager 를 찾을 수 없어 PushBegin 이 실패하고 클라이언트는 연결하지 못한다. 따라서, SessionManager 가 존재하지 않더라도 client 연결은 받고, 추후에 SessionManager 가 복구되면 client 정보를 추가(복구)하도록 하는 것이 좋겠다.

이 경우, 복구 process 가 진행되는 동안 새로운 user 가 연결(PushBegin) 되거나 연결이 삭제된 경우, 동기화를 고민해야할 것. SessionManager 의 user 정보와 local(push service)의 user 정보가 일치되어야 한다.

SessionManager 가 없는 상태에서 message 를 전송하면
```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'Message'.
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(String address)
   at K2svc.Net.GrpcClients.GetChannel(String backendAddress) in C:\work\local\K2\K2svc\Net\Grpc.cs:line 31
   at K2svc.Net.GrpcClients.GetClient[T](String backendAddress) in C:\work\local\K2\K2svc\Net\Grpc.cs:line 15
   at K2svc.Frontend.PushSampleService.Message(MessageRequest request, ServerCallContext context) in C:\work\local\K2\K2svc\Frontend\PushSampleService.cs:line 50
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

**Comment by alkee-allm** [comment]
SessionManager 가 다시 접근 가능해진 경우 복구(frontend push service 에 등록되어있는 users 들을 backend session manager 와 동기화)하는 로직이 필요.

동기화를 위해  다시 연결된 SessionManager 로 [AddUser](https://github.com/alkee-allm/k2proto/blob/c7ff78c1a7ed29370493edbf4886c9bfc51d25de/K2svc/proto/backend.proto#L24) 호출하는 순간

```
예외 발생: 'Grpc.Core.RpcException'(System.Private.CoreLib.dll)
'Grpc.Core.RpcException' 형식의 예외가 System.Private.CoreLib.dll에서 발생했지만 사용자 코드에서 처리되지 않았습니다.
Status(StatusCode=Cancelled, Detail="Bad gRPC response. Response did not have a content-type header.")



  | 이름 | 값 | 형식
-- | -- | -- | --
◢ | $exception | {"Status(StatusCode=Cancelled, Detail=\"Bad gRPC response. Response did not have a content-type header.\")"} | Grpc.Core.RpcException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2146233088 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "Status(StatusCode=Cancelled, Detail=\"Bad gRPC response. Response did not have a content-type header.\")" | string
  | Source | "System.Private.CoreLib" | string
  | StackTrace | "   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)\r\n   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)\r\n   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)\r\n   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)\r\n   at K2B.SessionManager.SessionManagerClient.AddUser(AddUserRequest request, CallOptions options) in C:\\work\\local\\K2\\K2svc\\obj\\Debug\\netcoreapp3.1\\BackendGrpc.cs:line 537\r\n   at K2B.SessionManager.SessionManagerClient.AddUser(AddUserRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in C:\\work\\local\\K2\\K2svc\\obj\\Debug\\netcoreapp3.1\\BackendGrpc.cs:line 533\r\n   at K2svc.Frontend.PushService.PushStreamDb.SyncUsersToSessionManager(SessionManagerClient target, String backendAddress) in C:\\work\\local\\K2\\K2svc\\Frontend\\PushService.cs:line 181\r\n   at K2svc.Backend.ServerHostBackend.UpdateBackend(UpdateBackendRequest request, ServerCallContext context) in C:\\work\\local\\K2\\K2svc\\Backend\\ServerHostBackend.cs:line 54\r\n   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.<ResolvedInterceptorInvoker>d__3.MoveNext()" | string
  | ▶ Status | {Status(StatusCode=Cancelled, Detail="Bad gRPC response. Response did not have a content-type header.")} | Grpc.Core.Status
  | StatusCode | Cancelled | Grpc.Core.StatusCode
  | ▶ TargetSite | {Void Throw()} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | ▶ Trailers | {Grpc.Core.Metadata} | Grpc.Core.Metadata
  | ▶ Static members |   |  
  | ▶ Non-Public members |   |  



 	K2svc.dll!K2B.SessionManager.SessionManagerClient.AddUser(K2B.AddUserRequest request, Grpc.Core.CallOptions options) 줄 537	C#
 	K2svc.dll!K2B.SessionManager.SessionManagerClient.AddUser(K2B.AddUserRequest request, Grpc.Core.Metadata headers, System.DateTime? deadline, System.Threading.CancellationToken cancellationToken) 줄 533	C#
>	K2svc.dll!K2svc.Frontend.PushService.PushStreamDb.SyncUsersToSessionManager(K2B.SessionManager.SessionManagerClient target, string backendAddress) 줄 181	C#
 	K2svc.dll!K2svc.Backend.ServerHostBackend.UpdateBackend(K2B.UpdateBackendRequest request, Grpc.Core.ServerCallContext context) 줄 54	C#
 	[외부 코드]	
 	K2svc.dll!K2svc.Filter.BackendValidator.UnaryServerHandler<K2B.UpdateBackendRequest, K2B.Null>(K2B.UpdateBackendRequest request, Grpc.Core.ServerCallContext context, Grpc.Core.UnaryServerMethod<K2B.UpdateBackendRequest, K2B.Null> continuation) 줄 38	C#
 	[외부 코드]	
 	K2svc.dll!K2svc.Startup.Configure.AnonymousMethod__0(Microsoft.AspNetCore.Http.HttpContext context, System.Func<System.Threading.Tasks.Task> next) 줄 79	C#
 	[외부 코드]	

```

**Comment by alkee-allm** [comment]
**모든 원흉**은 인증을 위한 header(Metadata) 문제.(#49) gRRPC client 를 사용할 때 header 를 빼먹기 쉬울거라고 예상했지만, 이렇게 직접 겪게되니 상당히 심각한 문제. dependency injection 을 통해 header 를 가져와야하는 문제는 부차적인 듯 하고, 적어도 호출시에 header 를 항상 신경써야하는 문제는 해결해야할 것. insecure channel 을 포기하더라도.

**Bad gRPC response 가 보이면 header 를 신경쓰자**
